const pool = require("../config/db");
const contentModel = require("../models/contentModel");
const syllabusModel = require("../models/syllabusModel");
const { generateEmbedding, pgVector } = require("../services/embedding");

/**
 * POST /content
 * Body: array of content records (all sharing the same syllabus_id).
 */
async function uploadContent(req, res) {
	try {
		const records = req.body;

		if (!Array.isArray(records) || records.length === 0) {
			return res.status(400).json({ error: "Body must be a non-empty array of content records" });
		}

		const syllabusId = records[0].syllabus_id;
		if (!syllabusId) {
			return res.status(400).json({ error: "Missing syllabus_id on records" });
		}

		// Validate syllabus_id exists
		const node = await syllabusModel.getById(syllabusId);
		if (!node) {
			return res.status(404).json({ error: `syllabus_id not found: ${syllabusId}` });
		}

		// Generate embeddings
		const rows = await Promise.all(
			records.map(async (r) => ({
				...r,
				embedding: pgVector(await generateEmbedding(`${r.title} ${r.body}`)),
			}))
		);

		const ids = await contentModel.replaceBaseContent(syllabusId, rows);
		return res.status(200).json({ syllabus_id: syllabusId, count: ids.length, ids });
	} catch (err) {
		console.error("uploadContent error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * GET /content?syllabus_id=&active=&tags=
 */
async function getContent(req, res) {
	try {
		const filters = {};
		if (req.query.syllabus_id) filters.syllabus_id = req.query.syllabus_id;
		if (req.query.active !== undefined) filters.active = req.query.active === "true";
		if (req.query.tags) filters.tags = req.query.tags.split(",");

		const rows = await contentModel.getContent(filters);
		return res.json(rows);
	} catch (err) {
		console.error("getContent error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * GET /content-views?user_id=&syllabus_id=
 */
async function getContentViews(req, res) {
	try {
		const { user_id, syllabus_id } = req.query;
		if (!user_id) {
			return res.status(400).json({ error: "Missing required query param: user_id" });
		}
		const rows = await contentModel.getContentViews(user_id, syllabus_id ?? null);
		return res.json(rows);
	} catch (err) {
		console.error("getContentViews error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * PUT /content-views
 * Body: { content_id, user_id }
 */
async function updateContentView(req, res) {
	try {
		const { content_id, user_id } = req.body;
		if (!content_id || !user_id) {
			return res.status(400).json({ error: "Missing required fields: content_id, user_id" });
		}
		const row = await contentModel.upsertContentView(content_id, user_id);
		return res.json(row);
	} catch (err) {
		console.error("updateContentView error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * POST /content/adaptive
 * Body: { syllabus_id, content_type?, title, body, tags? }
 *
 * Persists an adaptive content item generated by Claude (base_content = false).
 * The ingest script never overwrites adaptive items.
 */
async function createAdaptiveContent(req, res) {
	try {
		const { syllabus_id, content_type, title, body, tags } = req.body;

		if (!syllabus_id || !title || !body) {
			return res.status(400).json({ error: "Missing required fields: syllabus_id, title, body" });
		}

		const node = await syllabusModel.getById(syllabus_id);
		if (!node || node.level !== "subtopic") {
			return res.status(404).json({ error: `Subtopic ${syllabus_id} not found` });
		}

		const embedding = pgVector(await generateEmbedding(`${title} ${body}`));

		const result = await pool.query(
			`INSERT INTO content
			   (syllabus_id, active, base_content, content_type, title, body, tags, embedding)
			 VALUES ($1, true, false, $2, $3, $4, $5, $6)
			 RETURNING id`,
			[syllabus_id, content_type ?? "text", title, body, tags ?? [], embedding]
		);

		return res.status(201).json({ id: result.rows[0].id, syllabus_id, title });
	} catch (err) {
		console.error("createAdaptiveContent error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * GET /content/:id
 */
async function getContentItem(req, res) {
	try {
		const row = await contentModel.getContentById(req.params.id);
		if (!row) return res.status(404).json({ error: "Not found" });
		return res.json(row);
	} catch (err) {
		console.error("getContentItem error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

module.exports = { uploadContent, getContent, getContentViews, updateContentView, createAdaptiveContent, getContentItem };
