const pool = require("../config/db");
const questionModel = require("../models/questionModel");
const syllabusModel = require("../models/syllabusModel");
const { generateEmbedding, pgVector } = require("../services/embedding");

/**
 * POST /questions
 * Body: array of question records (all sharing the same syllabus_id).
 */
async function uploadQuestions(req, res) {
	try {
		const records = req.body;

		if (!Array.isArray(records) || records.length === 0) {
			return res.status(400).json({ error: "Body must be a non-empty array of question records" });
		}

		const syllabusId = records[0].syllabus_id;
		if (!syllabusId) {
			return res.status(400).json({ error: "Missing syllabus_id on records" });
		}

		// Validate syllabus_id exists
		const node = await syllabusModel.getById(syllabusId);
		if (!node) {
			return res.status(404).json({ error: `syllabus_id not found: ${syllabusId}` });
		}

		// Generate embeddings from question_text
		const rows = await Promise.all(
			records.map(async (r) => ({
				...r,
				embedding: pgVector(await generateEmbedding(r.question_text)),
			}))
		);

		const ids = await questionModel.replaceBaseQuestions(syllabusId, rows);
		return res.status(200).json({ syllabus_id: syllabusId, count: ids.length, ids });
	} catch (err) {
		console.error("uploadQuestions error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * GET /questions?syllabus_id=&difficulty=&active=
 */
async function getQuestions(req, res) {
	try {
		const filters = {};
		if (req.query.syllabus_id) filters.syllabus_id = req.query.syllabus_id;
		if (req.query.difficulty !== undefined) filters.difficulty = parseInt(req.query.difficulty, 10);
		if (req.query.active !== undefined) filters.active = req.query.active === "true";

		const rows = await questionModel.getQuestions(filters);
		return res.json(rows);
	} catch (err) {
		console.error("getQuestions error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * POST /questions/adaptive
 * Body: { syllabus_id, difficulty, question_type, question_text, options?, answer, tags? }
 *
 * Persists an adaptive question generated by Claude (base_content = false).
 */
async function createAdaptiveQuestion(req, res) {
	try {
		const { syllabus_id, difficulty, question_type, question_text, options, answer, tags } = req.body;

		if (!syllabus_id || difficulty === undefined || !question_type || !question_text || answer === undefined) {
			return res.status(400).json({
				error: "Missing required fields: syllabus_id, difficulty, question_type, question_text, answer",
			});
		}

		if (!["singleChoice", "multiChoice", "ordering", "freeText"].includes(question_type)) {
			return res.status(400).json({ error: `Invalid question_type: ${question_type}` });
		}

		const diff = Number(difficulty);
		if (!Number.isInteger(diff) || diff < 0 || diff > 4) {
			return res.status(400).json({ error: "difficulty must be an integer 0–4" });
		}

		const node = await syllabusModel.getById(syllabus_id);
		if (!node || node.level !== "subtopic") {
			return res.status(404).json({ error: `Subtopic ${syllabus_id} not found` });
		}

		const embedding = pgVector(await generateEmbedding(question_text));

		const result = await pool.query(
			`INSERT INTO question
			   (syllabus_id, active, base_content, difficulty, question_type, question_text, options, answer, tags, embedding)
			 VALUES ($1, true, false, $2, $3, $4, $5, $6, $7, $8)
			 RETURNING id`,
			[
				syllabus_id,
				diff,
				question_type,
				question_text,
				JSON.stringify(options ?? {}),
				JSON.stringify(answer),
				tags ?? [],
				embedding,
			]
		);

		return res.status(201).json({ id: result.rows[0].id, syllabus_id, question_type, difficulty: diff });
	} catch (err) {
		console.error("createAdaptiveQuestion error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

/**
 * GET /questions/:id
 */
async function getQuestionItem(req, res) {
	try {
		const row = await questionModel.getQuestionById(req.params.id);
		if (!row) return res.status(404).json({ error: "Not found" });
		return res.json(row);
	} catch (err) {
		console.error("getQuestionItem error:", err);
		return res.status(500).json({ error: "Internal server error" });
	}
}

module.exports = { uploadQuestions, getQuestions, createAdaptiveQuestion, getQuestionItem };
