/**
 * tutor.ai MCP plugin
 *
 * Exposes study tools to Claude via the Model Context Protocol (stdio transport).
 * All tools proxy to the tutor.ai REST API (configured via API_URL env var,
 * default http://localhost:3000). The plugin holds no DB connection of its own.
 *
 * Claude uses these tools to run interactive study sessions: fetching queue items,
 * showing content, collecting answers, and grading freeText responses inline.
 *
 * freeText grading flow (replaces the cron subprocess roundtrip):
 *   1. Claude calls submit_response → tool returns needs_grading=true + context
 *   2. Claude assesses the answer and immediately calls record_grade
 *   3. record_grade persists the score and runs the post-response pipeline
 *
 * Tools:
 *   get_queue        — fetch next study items (triggers queue refill if low)
 *   get_item_body    — fetch full body/text of a single queue item on-demand
 *   consume_item     — mark an item shown; records content views
 *   submit_response  — store answer; auto-grades all types except freeText
 *   record_grade     — persist Claude's freeText grade; runs pipeline
 *   create_content   — persist an adaptive content item generated by Claude
 *   create_question  — persist an adaptive question generated by Claude
 *   list_courses     — list available courses
 *   enroll           — enroll a user in a course
 *   get_progress     — show subtopic completion state for a user
 *
 * Context accumulation:
 *   Every get_item_body result lands in Claude's context window for the session.
 *   The DB returns SELECT * which includes embedding vector(384) — ~1,500 tokens of
 *   noise per item. For all-day sessions prefer the CLI client (app/index.js), which
 *   is stateless HTTP. To fix: filter embedding + unused fields in handleGetItemBody
 *   (mcp/src/tools/queue.js) before returning to Claude.
 *
 * Adaptive generation flow:
 *   submit_response / record_grade → pipeline returns struggling:[{subtopic_id,…}]
 *   Claude generates targeted content/questions for struggling subtopics
 *   Claude calls create_content / create_question to persist them
 *   Next get_queue call picks up the new items via scheduler.refillIfNeeded
 */

const { Server }               = require("@modelcontextprotocol/sdk/server/index.js");
const { StdioServerTransport } = require("@modelcontextprotocol/sdk/server/stdio.js");
const {
	CallToolRequestSchema,
	ListToolsRequestSchema,
	ErrorCode,
	McpError,
} = require("@modelcontextprotocol/sdk/types.js");

const { handleGetQueue, handleConsumeItem, handleGetItemBody } = require("./tools/queue");
const { handleSubmitResponse, handleRecordGrade }       = require("./tools/responses");
const { handleCreateContent, handleCreateQuestion }     = require("./tools/content");
const { handleListCourses, handleEnroll, handleGetProgress } = require("./tools/courses");

// ── Server ────────────────────────────────────────────────────────────────────

const server = new Server(
	{ name: "tutor-ai", version: "1.0.0" },
	{ capabilities: { tools: {} } }
);

// ── Tool definitions ──────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
	tools: [
		{
			name: "get_queue",
			description:
				"Get the next item from the user's queue (always returns 1 item). " +
				"Call this before each item — do not batch. " +
				"Items include both content (read to the user) and questions (ask the user). " +
				"Always call consume_item after displaying the item, then call get_queue again for the next one.",
			inputSchema: {
				type: "object",
				properties: {
					user_id: { type: "string" },
					limit:   { type: "number", description: "Max items to return (always 1)" },
				},
				required: ["user_id"],
			},
		},
		{
			name: "get_item_body",
			description:
				"Fetch the full body of a queue item before displaying it to the user. " +
				"Call this for every item returned by get_queue, passing item_type and item_id " +
				"from the queue item. For content items returns body and links. " +
				"For question items returns question_text, options, and answer.",
			inputSchema: {
				type: "object",
				properties: {
					item_type: { type: "string", description: '"content" or "question"' },
					item_id:   { type: "string", description: "UUID of the content or question row" },
				},
				required: ["item_type", "item_id"],
			},
		},
		{
			name: "consume_item",
			description:
				"Mark a queue item as consumed after displaying it to the user. " +
				"For content items this records a view, which is required for subtopic completion tracking. " +
				"Call immediately after showing the item.",
			inputSchema: {
				type: "object",
				properties: {
					queue_item_id: { type: "string" },
				},
				required: ["queue_item_id"],
			},
		},
		{
			name: "submit_response",
			description:
				"Record the user's answer to a question. " +
				"singleChoice, multiChoice, and ordering answers are graded automatically. " +
				"For freeText questions the tool returns needs_grading=true with the question text " +
				"and expected answer — you must assess the response and immediately call record_grade.",
			inputSchema: {
				type: "object",
				properties: {
					user_id:     { type: "string" },
					question_id: { type: "string" },
					user_answer: {
						description: "The user's answer. String for singleChoice/freeText; array for multiChoice/ordering.",
					},
				},
				required: ["user_id", "question_id", "user_answer"],
			},
		},
		{
			name: "record_grade",
			description:
				"Record your correctness score (0–4) for a freeText response. " +
				"Call this immediately after submit_response returns needs_grading=true. " +
				"0=wrong/blank  1=mostly wrong  2=partial  3=mostly correct  4=fully correct.",
			inputSchema: {
				type: "object",
				properties: {
					response_id: { type: "string" },
					user_id:     { type: "string" },
					correctness: { type: "number", description: "Integer 0–4" },
				},
				required: ["response_id", "user_id", "correctness"],
			},
		},
		{
			name: "create_content",
			description:
				"Persist an adaptive content item you have generated for a struggling user. " +
				"Call this when the pipeline returns a non-empty struggling array and you want to " +
				"add a targeted explanation, example, or summary for a subtopic. " +
				"The item is marked base_content=false and will never be overwritten by ingest. " +
				"It appears in the user's queue on the next get_queue call.",
			inputSchema: {
				type: "object",
				properties: {
					syllabus_id:  { type: "string",  description: "Subtopic ID (e.g. 'spanish-b2.1.1')" },
					content_type: { type: "string",  description: "One of: text, example, mnemonic, summary (default: text)" },
					title:        { type: "string" },
					body:         { type: "string",  description: "Full markdown content body" },
					tags:         { type: "array", items: { type: "string" }, description: "Should include a phase tag (phase:atomic / phase:complex / phase:integration)" },
				},
				required: ["syllabus_id", "title", "body"],
			},
		},
		{
			name: "create_question",
			description:
				"Persist an adaptive question you have generated for a struggling user. " +
				"Call this when the pipeline returns a non-empty struggling array to add " +
				"targeted practice questions at an appropriate difficulty. " +
				"The question is marked base_content=false and will never be overwritten by ingest. " +
				"It appears in the user's queue on the next get_queue call.",
			inputSchema: {
				type: "object",
				properties: {
					syllabus_id:   { type: "string",  description: "Subtopic ID" },
					difficulty:    { type: "number",  description: "Integer 0–4 (0=easiest). Use low difficulty (0–1) for struggling users." },
					question_type: { type: "string",  description: "singleChoice | multiChoice | ordering | freeText" },
					question_text: { type: "string" },
					options:       { description: "For singleChoice/multiChoice: object mapping option keys to text. Omit for freeText/ordering." },
					answer:        { description: "Correct answer. String for singleChoice/freeText; array for multiChoice/ordering." },
					tags:          { type: "array", items: { type: "string" }, description: "Should include a phase tag and relevant topic tags." },
				},
				required: ["syllabus_id", "difficulty", "question_type", "question_text", "answer"],
			},
		},
		{
			name: "list_courses",
			description: "List all available courses.",
			inputSchema: { type: "object", properties: {} },
		},
		{
			name: "enroll",
			description: "Enroll a user in a course. Safe to call multiple times (idempotent).",
			inputSchema: {
				type: "object",
				properties: {
					user_id:   { type: "string" },
					course_id: { type: "string" },
				},
				required: ["user_id", "course_id"],
			},
		},
		{
			name: "get_progress",
			description: "Get a user's subtopic completion state across all enrolled courses.",
			inputSchema: {
				type: "object",
				properties: {
					user_id: { type: "string" },
				},
				required: ["user_id"],
			},
		},
	],
}));

// ── Tool dispatch ─────────────────────────────────────────────────────────────

const HANDLERS = {
	get_queue:        (a) => handleGetQueue(a),
	get_item_body:    (a) => handleGetItemBody(a),
	consume_item:     (a) => handleConsumeItem(a),
	submit_response:  (a) => handleSubmitResponse(a),
	record_grade:     (a) => handleRecordGrade(a),
	create_content:   (a) => handleCreateContent(a),
	create_question:  (a) => handleCreateQuestion(a),
	list_courses:     ()  => handleListCourses(),
	enroll:           (a) => handleEnroll(a),
	get_progress:     (a) => handleGetProgress(a),
};

server.setRequestHandler(CallToolRequestSchema, async (request) => {
	const { name, arguments: args } = request.params;
	const handler = HANDLERS[name];
	if (!handler) {
		throw new McpError(ErrorCode.MethodNotFound, `Unknown tool: ${name}`);
	}
	try {
		const result = await handler(args ?? {});
		return {
			content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
		};
	} catch (err) {
		return {
			content: [{ type: "text", text: `Error: ${err.message}` }],
			isError: true,
		};
	}
});

// ── Start ─────────────────────────────────────────────────────────────────────

async function main() {
	const transport = new StdioServerTransport();
	await server.connect(transport);
	console.error("[tutor-ai] MCP plugin started");
}

main().catch((err) => {
	console.error("[tutor-ai] fatal:", err);
	process.exit(1);
});
